import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createDatabase, installDatabase } from './support/database.mjs';
test('check-in: edición diaria, apoyo privado, un solo aviso y caducidad', async()=>{
  const db=await createDatabase();
  try {
    await installDatabase(db);
    const a=randomUUID(),b=randomUUID(),other=randomUUID();
    const as=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
    const value=async(sql,args=[]) => (await db.query(sql,args)).rows[0].v;
    for(const id of [a,b,other]) await db.query('insert into auth.users values($1,$2,$3)',[id,id+'@test.invalid','{}']);
    await as(a);const couple=await value('select public.create_couple(current_date) v');
    await as(b);await db.query('select public.join_couple($1)',[couple.inviteCode??couple.invite_code]);
    await as(a);
    const first=await value("select to_jsonb(public.save_daily_checkin('calm',3,'Hoy estoy bien')) v");
    const edited=await value("select to_jsonb(public.save_daily_checkin('happy',4,'Terminé el examen')) v");
    assert.equal(first.id,edited.id);
    assert.equal(await value('select count(*)::int v from public.daily_checkins'),1);
    assert.equal(edited.energy,4);
    const projected=await value('select to_jsonb(p) v from public.profiles p where id=$1',[a]);
    assert.equal(projected.status_text,edited.phrase);
    assert.equal(projected.status_emoji,'😊');
    assert.equal(projected.status_source,'checkin');
    assert.equal(projected.status_expires_at,edited.expires_at);
    await db.query("select public.save_daily_checkin('calm',3,$1)",['a'.repeat(280)]);
    assert.equal(await value('select length(status_text) v from public.profiles where id=$1',[a]),280);
    await assert.rejects(db.query("select public.save_daily_checkin('happy',6,'')"),/no válido/);
    await assert.rejects(db.query('select public.respond_daily_checkin($1,$2)',[first.id,'Mi propio apoyo']),/no disponible/);
    await as(b);
    await db.query('select public.clear_daily_checkin($1)',[first.id]);
    assert.equal(await value('select count(*)::int v from public.daily_checkins'),1);
    assert.equal(await value("select count(*)::int v from public.notifications where dedupe_key like 'checkin:%'"),1);
    assert.equal(await value("select count(*)::int v from public.notifications where dedupe_key like 'status:%'"),0);
    await db.query('select public.respond_daily_checkin($1,$2)',[first.id,'Estoy aquí']);
    await db.query('select public.respond_daily_checkin($1,$2)',[first.id,'Estoy aquí']);
    assert.equal(await value('select count(*)::int v from public.checkin_responses'),1);
    await as(a);
    assert.equal(await value("select count(*)::int v from public.notifications where dedupe_key like 'checkin-response:%'"),1);
    await db.query('select public.clear_daily_checkin($1)',[first.id]);
    assert.equal(await value('select count(*)::int v from public.daily_checkins'),0);
    assert.equal(await value('select status_expires_at<=now() v from public.profiles where id=$1',[a]),true);
    const restored=await value("select to_jsonb(public.save_daily_checkin('happy',4,'De nuevo')) v");
    assert.equal(restored.id,first.id);
    await as(other);
    assert.equal(await value('select count(*)::int v from public.daily_checkins'),0);
    assert.equal(await value('select count(*)::int v from public.checkin_responses'),0);
    await assert.rejects(db.query('select public.respond_daily_checkin($1,$2)',[first.id,'No autorizado']),/no disponible/);
    await db.exec('reset role');await db.exec("update public.daily_checkins set expires_at=now()-interval '1 second'");
    await as(b);
    assert.equal(await value('select count(*)::int v from public.daily_checkins'),0);
    assert.equal(await value('select count(*)::int v from public.checkin_responses'),0);
    await assert.rejects(db.query('select public.respond_daily_checkin($1,$2)',[first.id,'Fuera de plazo']),/no disponible/);
    await db.exec('reset role');await db.exec('delete from public.daily_checkins where expires_at<=now()');
    assert.equal(await value('select count(*)::int v from public.checkin_responses'),0);
    assert.equal(await value('select status_text v from public.profiles where id=$1',[a]),'');
    await as(a);
    await db.query("select public.save_daily_checkin('happy',3,'Nuevo check-in')");
    await db.query("select public.set_status('Estado posterior','😊')");
    await db.exec('reset role');await db.exec('delete from public.daily_checkins');
    assert.equal(await value('select status_text v from public.profiles where id=$1',[a]),'Estado posterior');
  } finally {await db.close();}
});
