import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile } from './support/source.mjs';
import { createDatabase, installDatabase } from './support/database.mjs';

test('privacidad de lugares: pausa de servidor, reanudación y eventos anteriores', async () => {
  const db = await createDatabase();
  try {
    await installDatabase(db);
    const migration = await readFile(new URL('../supabase/migrations/20260911000100_place_sharing_privacy.sql', import.meta.url), 'utf8');
    await db.exec(migration);
    const a = randomUUID(), b = randomUUID();
    const as = async id => {
      await db.exec('reset role');
      await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id]);
      await db.exec('set role authenticated');
    };
    const value = async (sql, args = []) => (await db.query(sql, args)).rows[0].v;
    for (const id of [a,b]) await db.query('insert into auth.users values($1,$2,$3)', [id,id+'@test.invalid','{}']);
    await as(a);
    const couple = await value('select public.create_couple(current_date) v');
    await as(b);
    await db.query('select public.join_couple($1)', [couple.inviteCode ?? couple.invite_code]);
    await as(a);
    const place = await value("select public.create_geofence('Casa',40,-3,150) v");
    const oldTime = new Date(Date.now() - 10000).toISOString();
    const paused = await value('select to_jsonb(public.set_place_sharing(false,true)) v');
    assert.equal(paused.geofence_paused, true);
    assert.equal(paused.location_mode, 'off');
    const send = (time, transition = 'enter') => db.query('select public.record_geofence_transition($1,$2,$3,$4)', [place.id,randomUUID(),time,transition]);
    await assert.rejects(send(oldTime), /pausados/);
    await db.query('select public.set_place_sharing(true,false)');
    await assert.rejects(send(oldTime), /anterior/);
    await send(new Date(Date.now()+1000).toISOString());
    assert.equal(await value('select count(*)::int v from public.geofence_events'), 1);
    await as(b);
    await assert.rejects(db.query('select public.set_place_sharing(false,true,$1)', [a]), /Sesión necesaria/);
    await db.query('select public.set_place_sharing(false,false)');
    await as(a);
    assert.equal(await value('select geofence_paused v from public.user_settings where user_id=auth.uid()'), false);
    await assert.rejects(db.query('select public.set_place_sharing(true,true)'), /incompatibles/);
    const device = randomUUID();
    await db.query('select public.register_device($1,null,$2,$3,$4)', [device,'android','secret-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',a]);
    await db.query('select public.save_settings($1,$2)', [{location_mode:'balanced',history_enabled:true},device]);
    const sample = { user_id:a, device_id:device, sample_id:randomUUID(), captured_at:new Date(Date.now()-5000).toISOString(),
      lat:40.123456, lng:-3.123456, accuracy_m:5, speed_mps:2, heading:90 };
    await db.query('select public.publish_location_sample($1)', [sample]);
    await as(b);
    assert.equal(await value('select count(*)::int v from public.location_history'), 1);
    assert.equal(await value('select count(*)::int v from public.trips'), 1);
    await as(a);
    await db.query("select public.set_shared_precision('approximate')");
    await db.exec('reset role');
    await db.exec("update public.locations set updated_at=now()-interval '10 seconds'");
    await db.exec("update public.location_history set recorded_at=now()-interval '20 minutes'");
    await as(a);
    await db.query('select public.publish_location_sample($1)', [{ ...sample, sample_id:randomUUID(), captured_at:new Date().toISOString(), lat:40.126789 }]);
    await send(new Date(Date.now()+2000).toISOString(), 'exit');
    assert.equal(await value('select count(*)::int v from public.geofence_events'), 1, 'No publica nuevos eventos exactos de lugares');
    assert.equal(await value('select count(*)::int v from public.location_history'), 2, 'Conserva una nueva zona en el historial');
    await db.query('select public.set_approximate_place_events(true)');
    await send(new Date(Date.now()+3000).toISOString(), 'exit');
    assert.equal(await value('select count(*)::int v from public.geofence_events'), 2, 'Permite avisos concretos con autorización separada');
    await as(b);
    const location = await value('select to_jsonb(l) v from public.locations l');
    assert.equal(location.lat, 40.13);
    assert.equal(location.lng, -3.12);
    assert.ok(location.accuracy_m >= 2000);
    assert.equal(location.speed_mps, null);
    assert.equal(location.heading, null);
    assert.equal(await value('select count(*)::int v from public.location_history'), 1);
    const zone = await value('select to_jsonb(h) v from public.location_history h');
    assert.equal(zone.lat, 40.13);
    assert.equal(zone.lng, -3.12);
    assert.equal(zone.approximate, true);
    assert.ok(zone.accuracy_m >= 2000);
    assert.equal(await value('select count(*)::int v from public.trips'), 0);
  } finally { await db.close(); }
});
