import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createDatabase,installDatabase} from './support/database.mjs';

test('preguntas: respuesta privada, versiones y revelación única protegida en servidor',async()=>{
  const db=await createDatabase();
  try {
    await installDatabase(db);
    const a=randomUUID(),b=randomUUID(),outsider=randomUUID();
    const as=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
    const value=async(sql,args=[]) => (await db.query(sql,args)).rows[0].v;
    for(const id of [a,b,outsider]) await db.query('insert into auth.users values($1,$2,$3)',[id,id+'@test.invalid','{}']);
    await as(a);const couple=await value('select public.create_couple(current_date) v');
    await as(b);await db.query('select public.join_couple($1)',[couple.inviteCode??couple.invite_code]);
    await as(a);
    await assert.rejects(db.query("select public.get_daily_question('intimate')"),/Categoría/);
    const q=await value("select to_jsonb(public.get_daily_question('deep')) v");
    assert.equal((await value("select to_jsonb(public.get_daily_question('fun')) v")).id,q.id);
    await db.query('select public.answer_daily_question($1,$2,0)',[q.id,'Privada A']);
    assert.equal(await value('select count(*)::int v from public.question_answers'),1);
    await as(b);
    assert.equal(await value('select count(*)::int v from public.question_answers'),0);

    await assert.rejects(db.query('insert into public.question_answers(question_id,user_id,answer) values($1,$2,$3)',[q.id,b,'Lectura forzada']),/permission denied/);
    await as(a);
    await assert.rejects(db.query('select public.answer_daily_question($1,$2,0)',[q.id,'Edición obsoleta']),/Actualiza/);
    await db.query('select public.answer_daily_question($1,$2,1)',[q.id,'Privada A editada']);
    await as(b);await db.query('select public.answer_daily_question($1,$2,0)',[q.id,'Privada B']);
    assert.equal(await value('select count(*)::int v from public.question_answers'),2);
    await db.query('select public.answer_daily_question($1,$2,0)',[q.id,'Privada B']);
    await assert.rejects(db.query('select public.answer_daily_question($1,$2,1)',[q.id,'Cambio después de revelar']),/reveladas/);
    assert.equal(await value("select count(*)::int v from public.messages where metadata->>'kind'='question'"),1);
    assert.equal(await value("select count(*)::int v from public.notifications where dedupe_key like 'question:%'"),1);
    await as(outsider);
    assert.equal(await value('select count(*)::int v from public.question_answers'),0);
    await assert.rejects(db.query('select public.answer_daily_question($1,$2,0)',[q.id,'Tercero']),/no disponible/);
    await db.exec('reset role');
    assert.equal(await value("select count(*)::int v from pg_publication_tables where tablename='question_answers'"),0);
    await db.exec('delete from public.couple_daily_questions');
    await as(a);const next=await value("select to_jsonb(public.get_daily_question('fun')) v");
    await db.query('select public.answer_daily_question($1,$2,0)',[next.id,'Sin revelar']);
    await db.query('select public.skip_daily_question($1,true)',[next.id]);
    await db.query('select public.skip_daily_question($1,true)',[next.id]);
    assert.equal(await value('select count(*)::int v from public.question_answers'),0);
    assert.equal(await value('select count(*)::int v from public.question_skips'),1);
    await assert.rejects(db.query('select public.answer_daily_question($1,$2,0)',[next.id,'Reintento antiguo']),/Retómala/);
    await as(b);
    assert.equal(await value('select count(*)::int v from public.question_skips'),0);
    await db.query('select public.answer_daily_question($1,$2,0)',[next.id,'Solo B']);
    assert.equal(await value('select revealed_at is null v from public.couple_daily_questions where id=$1',[next.id]),true);
    await as(a);
    await db.query('select public.skip_daily_question($1,false)',[next.id]);
    assert.equal(await value('select count(*)::int v from public.question_skips'),0);
    assert.equal(await value('select love_streak_count v from public.couple_members where user_id=auth.uid()'),0);
    await db.exec('reset role');await db.query("update public.couple_daily_questions set closes_at=now()-interval '1 second' where id=$1",[next.id]);
    await as(a);
    await assert.rejects(db.query('select public.answer_daily_question($1,$2,0)',[next.id,'Tarde']),/terminado/);
    assert.equal(await value('select count(*)::int v from public.question_answers'),0);
    await db.exec('reset role');await db.exec('delete from public.couple_daily_questions');
    await as(a);
    const c=await value('select public.current_couple_id() v');
    const day=await value("select (now() at time zone 'Europe/Madrid')::date::text v");
    const customSql='select to_jsonb(public.create_custom_daily_question($1,$2,$3,$4)) v';
    const custom=await value(customSql,[c,a,day,'¿Qué plan nos apetece inventar?']);
    assert.equal(custom.category,'custom');
    assert.equal((await value(customSql,[c,a,day,custom.prompt])).id,custom.id);
    await assert.rejects(db.query(customSql,[c,a,'2000-01-01','Reintento de otro día']),/día ha cambiado/);
    await assert.rejects(db.query(customSql,[c,a,day,'Otra pregunta']),/Ya hay/);
    await as(b);
    await assert.rejects(db.query(customSql,[c,a,day,custom.prompt]),/no disponible/);
    assert.equal(await value('select prompt v from public.couple_daily_questions'),custom.prompt);
    await as(outsider);
    assert.equal(await value('select count(*)::int v from public.couple_daily_questions'),0);
    await assert.rejects(db.query(customSql,[c,outsider,day,'No autorizado']),/no disponible/);
    await as(b);
    await db.exec('reset role');await db.exec('delete from public.couple_daily_questions');
    await as(a);
    const preferencesSql='select public.set_question_category($1,$2,$3,$4,$5) v';
    assert.equal((await value('select public.get_question_preferences() v')).available.includes('intimate'),false);
    await assert.rejects(db.query(preferencesSql,['intimate',true,false,a,c]),/mayor de edad/);
    await db.query(preferencesSql,['intimate',true,true,a,c]);
    await assert.rejects(db.query("select public.get_daily_question('intimate')"),/Categoría no disponible/);
    await as(b);
    await assert.rejects(db.query(preferencesSql,['intimate',true,true,a,c]),/no disponible/);
    await db.query(preferencesSql,['intimate',true,true,b,c]);
    assert.equal((await value('select public.get_question_preferences() v')).available.includes('intimate'),true);
    const intimate=await value("select to_jsonb(public.get_daily_question('intimate')) v");
    assert.equal(intimate.category,'intimate');
    await as(a);await db.query(preferencesSql,['intimate',false,false,a,c]);
    assert.equal((await value('select public.get_question_preferences() v')).available.includes('intimate'),false);
    assert.equal(await value('select id v from public.couple_daily_questions'),intimate.id);
    await db.exec('reset role');await db.exec('delete from public.couple_daily_questions');
    await as(b);
    await assert.rejects(db.query("select public.get_daily_question('intimate')"),/Categoría no disponible/);
    await db.query(preferencesSql,['custom',false,false,b,c]);
    await as(a);
    await assert.rejects(db.query(customSql,[c,a,day,'Pregunta desactivada']),/Categoría no disponible/);
    await as(outsider);
    assert.equal(await value('select count(*)::int v from public.question_preferences'),0);
    await assert.rejects(db.query('select public.get_question_preferences()'),/no disponible/);
  } finally {await db.close();}
});
